### PR TITLE
[WIP] Specification

### PR DESCRIPTION
**Pull request by shalgrim**
not ready to be merged, just setting up the PR for collaboration between Astronomer and Zapier

### CODE REVIEW

**Comment by andrewhharmon** [comment]
Hey @shalgrim, I'll be taking a look at this. It looks like you are still waiting on some input for the specs, so I'll keep an eye out here.

**Comment by shalgrim** [comment]
Welcome, Andrew! If this is enough to go on, then let me know and we'll get Muness and Ry together to talk details. If not, let me know where you need more info. I don't know that I'm going to get any input from Muness or Dražen without specific questions =)

**Comment by andrewhharmon** [comment]
I think this work. I'll spend some time with it and once I have something working, we can go from there and tweak.

**Comment by andrewhharmon** [comment]
Hey @shalgrim, ran into a bit of an issue while working on this. SQS apparently only lets you ask for a message off the queue. You can not ask for all the messages. So if you have a few different services posting messages to the same queue, there is no way for a sensor to look at all the messages and determine if one is for its particular dag/task/execution date. Even if it's just one service with multiple messages for the same task (different execution date) you still can't loop through to check for the needed date. I can't think of a workaround for this at the moment. Do you have any more input on how you planned on using it?

**Comment by andrewhharmon** [comment]
@shalgrim, Could you possibly use an s3 sensor instead? You could have your processes drop a file with a key of dag_id/task_id/execution_date into a bucket somewhere and check for the existence of that file before moving forward.

**Comment by shalgrim** [comment]
Hm, interesting. Yeah, I guess we'd thought the SQS Sensor would have its own backing store. Seems like that might be possible with SQLite? The idea of a log db (e.g., Kafka) comes to mind, too...

**Comment by andrewhharmon** [comment]
@shalgrim can you provide a little more detail on how you pictured this? I'm not sure how a backing store in the sensor would help. If your queue has lots of different messages sitting in it for lots of different tasks/dates, there's no way to pull down all the messages and check for the one your sensor is interested in. Based on the distributed nature of SQS, you may never receive the specific message you're looking for unless another process was clearing out messages from the queue.

**Pull request merged**
